# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Kmatrix_ <- function(N, Pr1, Pr2, Pr3, Pr4) {
    .Call(`_SMCABCnJRNMM_Kmatrix_`, N, Pr1, Pr2, Pr3, Pr4)
}

perturb_continuous_withinprior_ <- function(theta_c_sampled, sigma_kernel, Pr_cont) {
    .Call(`_SMCABCnJRNMM_perturb_continuous_withinprior_`, theta_c_sampled, sigma_kernel, Pr_cont)
}

perturb_continuous_ <- function(theta_c_sampled, sigma_kernel) {
    .Call(`_SMCABCnJRNMM_perturb_continuous_`, theta_c_sampled, sigma_kernel)
}

nJRNMM_prior_ <- function(theta, draw, Pr_cont, N) {
    .Call(`_SMCABCnJRNMM_nJRNMM_prior_`, theta, draw, Pr_cont, N)
}

model_ <- function(N, sol) {
    .Call(`_SMCABCnJRNMM_model_`, N, sol)
}

